### ISSUE TITLE
Clerical Work

### ISSUE THREAD

**Issue by mattirizarry** [mattirizarry/CS351-Project#1]
### Description
The deliverables of the project include:
- A final report
- README.md file should explain to a developer how to get started with the project, and any other necessary information.
- ERD Diagram

### Stories
- #2 
- #3 
- #4 

### Acceptance Criteria
- [ ] Report is completed with sufficient detail and length.
- [ ] ERD Diagram correctly depicts the relations in the live database.
- [ ] README.md file is present with sufficient detail.

### Timeline
To be completed no later than the end of the project.
