### ISSUE TITLE
Representative Authentication

### ISSUE THREAD

**Issue by mattirizarry** [mattirizarry/CS351-Project#5]
### Description
A representative from the company should be able to login with a username and password. They should then be directed to their dashboard upon a successful authentication. Otherwise they should be denied access.

### User Stories
List the specific user stories that make up the epic. These should be broken down into smaller, more manageable pieces of functionality that can be prioritized and completed in a single sprint.
- #6 
- #7 
- #8

### Acceptance Criteria
Clearly define the criteria that must be met in order for the epic to be considered complete. This may include specific functional requirements, performance metrics, or other criteria that must be met in order to meet the business objectives of the epic.
- [ ] User can login with a username and password
- [ ] Users can have different levels of permissions
- [ ] CRUD, or any operations to the database need authentication first.

### Timeline
To be completed before EOD Wednesday, April 12th. 

### QA
QA should be performed before progress meeting on April 14th.
